//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Envios.Especiais.Infra.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Envios.Especiais.Infra.Service.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            /*font-family: CALIBRI LIGHT;
        ///            font-size: 15px;*/
        ///            font-family: VERDANA;
        ///            font-size: 15px;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;text-align: justify; margin-left: auto; margin-right: auto; width: 650px;padding-left: 20px;padding-right: 20px&quot; border=&quot;0&quot; cellpadding=&quot;2&quot; cellspacing=&quot;2&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailAndamentoMeridioQdtPublicacoesNaoCapturadas {
            get {
                return ResourceManager.GetString("EmailAndamentoMeridioQdtPublicacoesNaoCapturadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            /*font-family: CALIBRI LIGHT;
        ///            font-size: 15px;*/
        ///            font-family: VERDANA;
        ///            font-size: 15px;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;text-align: justify; margin-left: auto; margin-right: auto; width: 650px;padding-left: 20px;padding-right: 20px&quot; border=&quot;0&quot; cellpadding=&quot;2&quot; cellspacing=&quot;2&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailDistribuicao {
            get {
                return ResourceManager.GetString("EmailDistribuicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            /*font-family: CALIBRI LIGHT;
        ///            font-size: 15px;*/
        ///            font-family: VERDANA;
        ///            font-size: 15px;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;text-align: justify; margin-left: auto; margin-right: auto; width: 650px;padding-left: 20px;padding-right: 20px&quot; border=&quot;0&quot; cellpadding=&quot;2&quot; cellspacing=&quot;2&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailDistribuicaoSituacaoPendente {
            get {
                return ResourceManager.GetString("EmailDistribuicaoSituacaoPendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            /*font-family: CALIBRI LIGHT;
        ///            font-size: 15px;*/
        ///            font-family: VERDANA;
        ///            font-size: 15px;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;text-align: justify; margin-left: auto; margin-right: auto; width: 650px;padding-left: 20px;padding-right: 20px&quot; border=&quot;0&quot; cellpadding=&quot;2&quot; cellspacing=&quot;2&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailJuridicoMeridioQdtPublicacoesNaoCapturadas {
            get {
                return ResourceManager.GetString("EmailJuridicoMeridioQdtPublicacoesNaoCapturadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            /*font-family: CALIBRI LIGHT;
        ///            font-size: 15px;*/
        ///            font-family: VERDANA;
        ///            font-size: 15px;
        ///        }
        ///    &lt;/style&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table style=&quot;text-align: justify; margin-left: auto; margin-right: auto; width: 650px;padding-left: 20px;padding-right: 20px&quot; border=&quot;0&quot; cellpadding=&quot;2&quot; cellspacing=&quot;2&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailKurierSituacaoPendente {
            get {
                return ResourceManager.GetString("EmailKurierSituacaoPendente", resourceCulture);
            }
        }
    }
}
